### ISSUE TITLE
A lot of types are missing in .netcore

### ISSUE THREAD

**Issue by Shadowblitz16** [NogginBops/ImGui.NET_OpenTK_Sample#12]
A lot of types are missing in .netcore like GraphicsMode, GameWindowFlags, DisplayDevice and GraphicsContextFlags

I have OpenTK installed through NuGet

![image](https://user-images.githubusercontent.com/2453707/96326534-53566e00-0fe6-11eb-93ac-d4203b46b5ba.png)

intellisense can't find them either

here is my csproj file 
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <RootNamespace>GameSharp.Editor</RootNamespace>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <OutputPath></OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="lib\Internal\**" />
    <EmbeddedResource Remove="lib\Internal\**" />
    <None Remove="lib\Internal\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Editor.cs" />
    <Compile Remove="Program.cs" />
    <Compile Remove="Util.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ImGui.NET" Version="1.78.0" />
    <PackageReference Include="OpenTK" Version="4.0.3" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="lib\" />
  </ItemGroup>

</Project>
```

**Comment by NogginBops** [comment]
What branch of the repository are you using?
There is a OpenTK 4.0 branch that is on .net core, though it's still on the prerelease versions of opentk.
I will try to update it soon to opentk 4.0.3.

**Comment by Shadowblitz16** [comment]
I was using master. 
ok thankyou so much.

**Comment by NogginBops** [comment]
I've updated the opentk 4.0 branch so it now uses the opentk 4.0.3 version.

**Comment by NogginBops** [comment]
Closing as this is fixed now. And the opentk 4 branch is now the default branch so this issue will be less prevalent.
