### ISSUE TITLE
Please upload this to nuget.

### ISSUE THREAD

**Issue by Shadowblitz16** [NogginBops/ImGui.NET_OpenTK_Sample#13]
I think it would be nice if this could be uploaded to nuget

**Comment by NogginBops** [comment]
To upload this to nuget I would want to remove the `Texture` and `Shader` classes as users don't want name collisions with my versions.
But one of the biggest reasons for not making a nuget package of this is that it will lock you to the opentk version that this project supports, it's much nicer to distribute this as source so people can modify it to their needs.

**Comment by Shadowblitz16** [comment]
oh ok that makes sense
