### ISSUE TITLE
Cursor offset

### ISSUE THREAD

**Issue by Khhs167** [NogginBops/ImGui.NET_OpenTK_Sample#17]
The cursor has a notable offset between window position and the position ImGUI uses, any idea how to fix it?

**Comment by NogginBops** [comment]
Can you show a screenshot of this behavior? 
Are you using anything like a different viewport or something like that while not compensating for it in ImGui?

**Comment by Khhs167** [comment]
I managed to fix it. Unsure how i did it, but I am fairly certain the fix was in `GameWindow.OnResize` where I set the size with `controller.WindowResized(Size.X, Size.Y);` whereas the fix was to simply to do `controller.WindowResized(e.X, e.Y);`, and `e` is the ResizeEventArgs passed into the function.
Thanks for the quick response and I hope anyone who has the same issue finds this useful!
