### ISSUE TITLE
System.AccessViolationException in ImGuiController.cs

### ISSUE THREAD

**Issue by lumentae** [NogginBops/ImGui.NET_OpenTK_Sample#21]
If you build this project & start it, you will get a System.AccessViolationException from ImGuiController.cs

Please fix this! 

Thank you 😊

**Comment by NogginBops** [comment]
What branch of this repo are you using? 
What OS are you running on? 
What graphics card do you have?

**Comment by lumentae** [comment]
1. opentk4.0
2. Windows 11
3. Nvidia Geforce 840M

**Comment by NogginBops** [comment]
Ok, can you tell me where in the code it crashes?

**Comment by lumentae** [comment]
Should be this line
https://github.com/NogginBops/ImGui.NET_OpenTK_Sample/blob/df03faef260d7cddff07cae2c74f75390bbe34be/Dear%20ImGui%20Sample/ImGuiController.cs#L68

**Comment by NogginBops** [comment]
Are your drivers up to date and does your drivers support OpenGL 4.5?
The current `opentk4.0` branch uses opengl 4.5 features that might not be available, if that is the case I would recommend you to either test the `opentk4.0-dev` branch which only requires opengl 3.3.

**Comment by lumentae** [comment]
I will try that. Thank you.

**Comment by lumentae** [comment]
Okay works now!
