### ISSUE TITLE
Consider making this inherit GameWindow

### ISSUE THREAD

**Issue by Shadowblitz16** [NogginBops/ImGui.NET_OpenTK_Sample#25]
Consider making this inherit GameWindow.
Maybe call it ImGuiWindow.
```
public class Program : ImGuiWindow
{
    public override void OnGui()
    {
        ImGui.Begin()

        ImGui.End()
    }
}
```

**Comment by NogginBops** [comment]
I will not be doing this. 
This sample is meant to be an easy plug and play class that you can just add to your existing project and get going. I see no value doing this myself over users implementing this themselves if they want to.
