### ISSUE TITLE
Gl.PolygonMode state not being saved

### ISSUE THREAD

**Issue by Adam-Bakerr** [NogginBops/ImGui.NET_OpenTK_Sample#28]
When Changing the Gl.Drawmode to either line or polygon imgui also renders as such, making it unusable when in point mode
Images Attached
![1302 15_07_2023 12_04_23](https://github.com/NogginBops/ImGui.NET_OpenTK_Sample/assets/91663985/e3fe7d8d-7b21-4ea3-ae6e-9d17b043bbcc)

**Comment by NogginBops** [comment]
I've fixed this on the `opentk3`, `opentk4.0`, and `opentk5` branches of this repo.
